//ask user to enter a number for age, to validate

//pull the number and country to validate
// now check if the age inputted is allowed for each event legally, then input each out
    //is age to drive 16 (is the nominal age) if underage, they need a permit and can only drive with an adult during the day
    //is age to drink 21 US 18 or 16 EU and other countries (add this to version 2) if underage they cannot drink
    //is age to rent a car affordably 25, if not say you can not yet able to rent cars affordably yet
    //is agge 55 or older, you can join AARP, if not say you can not join AARP yet
    //is age 65 or older, you can retire, if not say you can not retire yet
//the botom is generated by GitHub Co-Pilot
//ask user to enter a number for age, to validate
var age = prompt("Please enter your age in years: ");
//pull the number and country to validate
var country = prompt("Please enter your country: ");
// now check if the age inputted is allowed for each event legally, then input each out
    //is age to drive 16 (is the nominal age) if underage, they need a permit and can only drive with an adult during the day
if (age >= 16 && country == "USA") {
} else if (age >= 18 && country == "EU") {}
    //is age to drink 21 US 18 or 16 EU and other countries (add this to version 2) if underage they cannot drink
if (age >= 21 && country == "USA") {} else if (age >= 18 && country == "EU") {}
    //is age to rent a car affordably 25, if not say you can not yet able to rent cars affordably yet
if (age >= 25) {}
    //is agge 55 or older, you can join AARP, if not say you can not join AARP yet
if (age >= 55) {}
    //is age 65 or older, you can retire, if not say you can not retire yet
if (age >= 65) {}
//print out the results
console.log("You are " + age + " years old and live in " + country + ".");
