const readline = require("readline");

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
})
//ask user to enter a number for age, to validate
function ageChecker(){
    rl.question("Enter in a number: ",);
}
//the bottom is generated by GitHub Co-Pilot

//pull the number and country to validate

// now check if the age inputted is allowed for each event legally, then input each out

    //is age to drive 16 (is the nominal age) if underage, they need a permit and can only drive with an adult during the day

    //is age to drink 21 US 18 or 16 EU and other countries (add this to version 2) if underage they cannot drink
    
    //is age to rent a car affordably 25, if not say you can not yet able to rent cars affordably yet
    
    //is agge 55 or older, you can join AARP, if not say you can not join AARP yet
    
    //is age 65 or older, you can retire, if not say you can not retire yet

