const readline = require("readline");

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
})
//ask user to enter a number for age, to validate
function ageChecker(){
    rl.question("Enter in a number: ", (age)=>{
        let parsedAge = parseInt(age);
        //if under 16, tell them they can't drive
        if (parsedAge < 16){
            console.log('You can\'t drive')
        } 
        else {
            console.log('You can drive')
        }
        //if under 18, tell them they can't hate from outside the club, because they can't even get in
        if (parsedAge < 18){
            console.log('You can\'t hate from outside the club, because you can\'t even get in')
        } else {
            console.log('You can hate from outside the club, because you can get in')
        }
        //if under 21, tell them they can't drink
        if (parsedAge < 21){
            console.log('You can\'t drink')
        } else {
            console.log('You can drink')
        }
        //if under 25, tell them they can't rent cars affordably
        if (parsedAge < 25){
            console.log('You can\'t rent cars affordably')
        }else { 
            console.log('You can rent cars affordably')
        }
        //if under 30, tell them they can't rent fancy cars affordably
        if (parsedAge < 30){
            console.log('You can\'t rent fancy cars affordably')
        } else {
            console.log('You can rent fancy cars affordably')
        }
        //if under over 30, tell them there is nothing left to look forward to
        if (parsedAge > 30){
            console.log('There is nothign left to look forward to, expect retirement and death')
        }else {
            console.log('You have a lot to look forward to')
        }
        if (parsedAge > 116){
            console.log('You are the oldest person alive, how are you still alive. Are you even human.')
        }else {
            console.log('You just old')
        }
        rl.close();
    })
}
//the bottom is generated by GitHub Co-Pilot

//pull the number and country to validate

// now check if the age inputted is allowed for each event legally, then input each out

    //is age to drive 16 (is the nominal age) if underage, they need a permit and can only drive with an adult during the day

    //is age to drink 21 US 18 or 16 EU and other countries (add this to version 2) if underage they cannot drink
    
    //is age to rent a car affordably 25, if not say you can not yet able to rent cars affordably yet
    
    //is agge 55 or older, you can join AARP, if not say you can not join AARP yet
    
    //is age 65 or older, you can retire, if not say you can not retire yet

